service: serverless-chaos-demo-nodejs
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:ssm:${opt:region, self:provider.region}:*:parameter/'
            - Ref: failureLambdaParameter1
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:ssm:${opt:region, self:provider.region}:*:parameter/'
            - Ref: failureLambdaParameter2
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:ssm:${opt:region, self:provider.region}:*:parameter/'
            - Ref: failureLambdaParameter3
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/'
            - Ref: failureLambdaTable

functions:
  failureLambdaFunction1:
    handler: index.handler
    timeout: 3
    environment:
      FAILURE_INJECTION_PARAM:
        Ref: failureLambdaParameter1
      FAILURE_INJECTION_TABLE:
        Ref: failureLambdaTable
    events:
      - http:
          path: failureLambdaFunction1/
          method: get
          cors: true
  failureLambdaFunction2:
    handler: index.handler
    timeout: 3
    environment:
      FAILURE_INJECTION_PARAM:
        Ref: failureLambdaParameter2
      FAILURE_INJECTION_TABLE:
        Ref: failureLambdaTable
    events:
      - http:
          path: failureLambdaFunction2/
          method: get
          cors: true
  failureLambdaFunction3:
    handler: index.handler
    timeout: 3
    environment:
      FAILURE_INJECTION_PARAM:
        Ref: failureLambdaParameter3
      FAILURE_INJECTION_TABLE:
        Ref: failureLambdaTable
    events:
      - http:
          path: failureLambdaFunction3/
          method: get
          cors: true

resources:
  Resources:
    failureLambdaParameter1:
      Type: 'AWS::SSM::Parameter'
      Properties:
        Type: String
        Value: '{"isEnabled": false, "failureMode": "latency", "rate": 1, "minLatency": 100, "maxLatency": 400, "exceptionMsg": "Exception message!", "statusCode": 404, "diskSpace": 100, "denylist": ["s3.*.amazonaws.com", "dynamodb.*.amazonaws.com"]}'
    failureLambdaParameter2:
      Type: 'AWS::SSM::Parameter'
      Properties:
        Type: String
        Value: '{"isEnabled": false, "failureMode": "latency", "rate": 1, "minLatency": 100, "maxLatency": 400, "exceptionMsg": "Exception message!", "statusCode": 404, "diskSpace": 100, "denylist": ["s3.*.amazonaws.com", "dynamodb.*.amazonaws.com"]}'
    failureLambdaParameter3:
      Type: 'AWS::SSM::Parameter'
      Properties:
        Type: String
        Value: '{"isEnabled": false, "failureMode": "latency", "rate": 1, "minLatency": 100, "maxLatency": 400, "exceptionMsg": "Exception message!", "statusCode": 404, "diskSpace": 100, "denylist": ["s3.*.amazonaws.com", "dynamodb.*.amazonaws.com"]}'
    failureLambdaTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - ./client/**
    - .vscode
    - .serverless
